# Real Time Location System
## MSDS 7333 - Section 404
## Unit 6: Case Study

[Data Science @ Southern Methodist University](https://datascience.smu.edu/)

# Table of Contents
* [Team Members](#Team-Members)
* [Abstract](#Abstract)
* [Introduction](#Introduction)
* [Literature Review](#Literature-Review)
* [Background](#Background)
* [Methods](#Methods)
* [Results](#Results)
* [Future Work, Discussion, and Conclusion](#Conclusion)
* [References](#References)

# <a name="Team-Members"></a>Team Members
* [Jostein Barry-Straume](https://github.com/josteinstraume)

# <a name="Abstract"></a>Abstract

# <a name="Introduction"></a>Introduction

# <a name="Literature-Review"></a>Literature Review

# <a name="Background"></a>Background
### Import Dataset


| Variable | Description |
| :------: | :-----------: |
| text | text | 

In [1]:
#%%capture
#import warnings
#warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df = pd.read_csv('../data/offline_final_trace.txt', sep=';', delimiter='\n')


In [2]:
#%load_ext rpy2.ipython

In [3]:
df.head()

# timestamp=2006-02-11 08:31:58
0                                         # usec=250
1                                  # minReadings=110
2  t=1139643118358;id=00:02:2D:21:0F:33;pos=0.0,0...
3  t=1139643118744;id=00:02:2D:21:0F:33;pos=0.0,0...
4  t=1139643119002;id=00:02:2D:21:0F:33;pos=0.0,0...

In [4]:
# Sources:
# http://rpy.sourceforge.net/rpy2/doc-2.4/html/overview.html#installation
# http://rpy2.readthedocs.io/en/version_2.8.x/introduction.html
# 
import rpy2
rpy2.__path__
#from rpy2.robjects.packages import importr


['/Users/Jostein/anaconda3/lib/python3.6/site-packages/rpy2']

In [5]:
print(rpy2.__version__)

2.9.1


In [6]:
%load_ext rpy2.ipython

In [17]:
#import rpy2
#from rpy2.robjects.packages import *
from rpy2.robjects.packages import importr
#from rpy2.robjects import readLines
import rpy2.robjects as robjects
base = importr('base')

In [18]:
print(base)

rpy2.robjects.packages.Package as a <module 'base'>


In [19]:
txt = base.readLines('../data/offline_final_trace.txt')

In [42]:
from rpy2.robjects.vectors import DataFrame
from rpy2.robjects.packages import importr, data

r_base = importr('base')

datasets = importr('datasets')
faithful_data = data(datasets).fetch('faithful')['faithful']

edsummary = r_base.summary(faithful_data.rx2("eruptions"))
for k, v in edsummary.items():
   print("%s: %.3f\n" %(k, v))

graphics = importr('graphics')

print("Stem-and-leaf plot of Old Faithful eruption duration data")
graphics.stem(faithful_data.rx2("eruptions"))

Min.: 1.600

1st Qu.: 2.163

Median: 4.000

Mean: 3.488

3rd Qu.: 4.454

Max.: 5.100

Stem-and-leaf plot of Old Faithful eruption duration data


  The decimal point is 
1 digit(s) to the left of the |


  16 | 
0
7
0
3
5
5
5
5
5
5
8
8


  18 | 
0
0
0
0
2
2
2
3
3
3
3
3
3
3
5
5
7
7
7
7
7
7
7
7
8
8
8
8
2
2
3
3
5
7
7
7
8
8
8


  20 | 
0
0
0
0
2
2
2
3
3
7
8
8
0
0
0
3
5
7
7
8


  22 | 
0
0
0
2
3
3
5
5
7
8
0
2
3
5
7
8


  24 | 
0
0
2
2
8


  26 | 
2
3


  28 | 
0
8
0


  30 | 
7


  32 | 
2
3
3
7


  34 | 
2
5
0
0
7
7


  36 | 
0
0
0
0
8
2
3
5
7
7


  38 | 
2
3
3
3
3
3
5
5
8
2
2
2
5
5
7
7


  40 | 
0
0
0
0
0
0
3
3
5
7
7
8
8
8
8
8
0
0
2
2
3
3
5
5
5
5
7
7
7
7
8


  42 | 
0
3
3
3
5
5
5
5
7
7
8
8
0
0
2
3
3
3
3
3
5
5
5
5
7
7
7
7
8


  44 | 
0
2
2
2
2
3
3
5
5
5
7
7
8
0
0
0
0
0
0
0
0
2
3
3
3
3
3
5
7
7
7
8
8
8
8


  46 | 
0
0
0
0
2
3
3
3
5
7
7
0
0
0
0
0
0
2
3
5
7
8


  48 | 
0
0
0
0
0
0
2
2
3
3
5
8
0
0
3
3
3


  50 | 
0
3
7
0






rpy2.rinterface.NULL

In [44]:
from rpy2 import *
from rpy2.robjects.vectors import DataFrame
from rpy2.robjects.packages import importr, data

r_base = importr('base')
txt = r_base.readLines('../data/offline_final_trace.txt')
r_base.sum(r_base.substr(txt,1,1) == "#")

R object with classes: ('integer',) mapped to:
<IntVector - Python:0x1056a3888 / R:0x7fb6768369c8>
[0]

In [28]:
base.sum(base.substr(txt,1,1) == "#")

R object with classes: ('integer',) mapped to:
<IntVector - Python:0x10d35fc48 / R:0x7fb67a3161c8>
[0]

In [45]:
base.length(txt)

R object with classes: ('integer',) mapped to:
<IntVector - Python:0x10d280e48 / R:0x7fb676836a28>
[151,392]

In [46]:
print(txt[1:10])

[1] "# usec=250"                                                                                                                                                                                                                                                                                                                                                                                                                                                      
[2] "# minReadings=110"                                                                                                                                                                                                                                                                                                                                                                                                                                               
[3] "t=1139643118358;id=00:02:2D:21:0F:33;pos=0.0,0.0,0.0;degree=0.0;00:14:bf:b1:97:8a=-38

In [59]:
didthiswork = r_base.strsplit(txt, ";")

In [207]:
didthiswork[3]

R object with classes: ('character',) mapped to:
<StrVector - Python:0x10db66148 / R:0x7fb667b9bca0>
['t=113964..., 'id=00:02..., 'pos=0.0,..., 'degree=0..., ..., '00:0f:a3..., '00:0f:a3..., '02:64:fb..., '02:00:42...]

In [69]:
for item in didthiswork:
    tmp = r_base.matrix(tokens[ - (1:10) ], ncol = 4, byrow = TRUE)
    r_base.cbind(matrix(tokens[c(2, 4, 6:8, 10)], nrow = nrow(tmp), ncol = 6, byrow = TRUE), tmp)

SyntaxError: invalid syntax (<ipython-input-69-957956fae86a>, line 2)

In [73]:
processLine = base.function(x)
{
    tokens <- r_base.strsplit(x, "[;=,]")[[1]]
    tmp <- r_base.matrix(tokens[ - (1:10) ], ncol = 4, byrow = TRUE)
    r_base.cbind(matrix(tokens[c(2, 4, 6:8, 10)], nrow = nrow(tmp), ncol = 6, byrow = TRUE), tmp)
}

SyntaxError: invalid syntax (<ipython-input-73-e5605300c71c>, line 4)

In [77]:
tokens = r_base.strsplit(x, "[;=,]")[[1]]

NameError: name 'x' is not defined

In [100]:
from rpy2.robjects.packages import SignatureTranslatedAnonymousPackage
from rpy2.robjects.vectors import DataFrame
from rpy2.robjects.packages import importr, data

r_base = importr('base')

string = """
txt <- function()
{
    return(readLines('../data/offline_final_trace.txt'))
}

processLine <- function(x) {
    tokens = strsplit(x, "[;=,]")[[1]]
    if (length(tokens) == 10) {
        return(NULL)
    }
    tmp = matrix(tokens[ - (1:10) ], , 4, byrow = TRUE)
    cbind(matrix(tokens[c(2, 4, 6:8, 10)], nrow(tmp), 6, byrow = TRUE), tmp)
}

lines <- function(x) {
    return(x[ substr(x, 1, 1) != "#" ])
}

tmp <- function(x, y) {
    return(lapply(x, y))
}

offline <- function(x) {
    return(as.data.frame(do.call("rbind", x), stringsAsFactors = FALSE))
}

"""

tutorial = SignatureTranslatedAnonymousPackage(string, "tutorial")

In [119]:
df_offline = tutorial.offline(tutorial.tmp(tutorial.lines(tutorial.txt()), tutorial.processLine(x)))

NameError: name 'x' is not defined

In [103]:
txt = tutorial.txt()

In [203]:
txt

R object with classes: ('character',) mapped to:
<StrVector - Python:0x10d188588 / R:0x10fb14000>
['# timest..., '# usec=2..., '# minRea..., 't=113964..., ..., 't=114193..., 't=114193..., 't=114193..., '# Trace ...]

In [110]:
lines = tutorial.lines(txt)

In [204]:
lines

R object with classes: ('character',) mapped to:
<StrVector - Python:0x10e32d1c8 / R:0x10e1f2000>
['t=113964..., 't=113964..., 't=113964..., 't=113964..., ..., 't=114193..., 't=114193..., 't=114193..., 't=114193...]

In [123]:
temp = r_base.lapply(lines, function(x)
    tokens = strsplit(x, "[;=,]")[[1]]
    if (length(tokens) == 10) {
        return(NULL)
    }
    tmp = matrix(tokens[ - (1:10) ], , 4, byrow = TRUE)
    cbind(matrix(tokens[c(2, 4, 6:8, 10)], nrow(tmp), 6, byrow = TRUE), tmp))

SyntaxError: invalid syntax (<ipython-input-123-442294bcccf3>, line 2)

In [129]:
for line in lines:
    tmp = tutorial.processLine(line)

In [126]:
lines

R object with classes: ('character',) mapped to:
<StrVector - Python:0x10e32d1c8 / R:0x10e1f2000>
['t=113964..., 't=113964..., 't=113964..., 't=113964..., ..., 't=114193..., 't=114193..., 't=114193..., 't=114193...]

In [130]:
lines[1]

't=1139643118744;id=00:02:2D:21:0F:33;pos=0.0,0.0,0.0;degree=0.0;00:14:bf:b1:97:8a=-38,2437000000,3;00:0f:a3:39:e1:c0=-54,2462000000,3;00:14:bf:b1:97:90=-56,2427000000,3;00:14:bf:3b:c7:c6=-67,2432000000,3;00:14:bf:b1:97:81=-66,2422000000,3;00:14:bf:b1:97:8d=-70,2442000000,3;00:0f:a3:39:e0:4b=-79,2462000000,3;00:0f:a3:39:dd:cd=-73,2412000000,3;00:0f:a3:39:e2:10=-83,2437000000,3;02:00:42:55:31:00=-85,2457000000,1'

In [134]:
r_base.dim(tmp)

R object with classes: ('integer',) mapped to:
<IntVector - Python:0x10d188b88 / R:0x7fb6686d5d28>
[8, 10]

In [142]:
print(lines[0])

t=1139643118358;id=00:02:2D:21:0F:33;pos=0.0,0.0,0.0;degree=0.0;00:14:bf:b1:97:8a=-38,2437000000,3;00:14:bf:b1:97:90=-56,2427000000,3;00:0f:a3:39:e1:c0=-53,2462000000,3;00:14:bf:b1:97:8d=-65,2442000000,3;00:14:bf:b1:97:81=-65,2422000000,3;00:14:bf:3b:c7:c6=-66,2432000000,3;00:0f:a3:39:dd:cd=-75,2412000000,3;00:0f:a3:39:e0:4b=-78,2462000000,3;00:0f:a3:39:e2:10=-87,2437000000,3;02:64:fb:68:52:e6=-88,2447000000,1;02:00:42:55:31:00=-84,2457000000,1


In [162]:
offline = r_base.matrix(nrow=1,ncol=10)
for line in lines:
    tmp = tutorial.processLine(line)
    offline = r_base.rbind(offline, tmp)
    

In [153]:
offline = r_base.matrix(nrow=1,ncol=10)
testMat = r_base.matrix(nrow=1,ncol=10)
print(offline)
print(testMat)
testy = r_base.rbind(offline, testMat)
print(testy)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]   NA   NA   NA   NA   NA   NA   NA   NA   NA    NA

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]   NA   NA   NA   NA   NA   NA   NA   NA   NA    NA

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]   NA   NA   NA   NA   NA   NA   NA   NA   NA    NA
[2,]   NA   NA   NA   NA   NA   NA   NA   NA   NA    NA



In [164]:
r_base.dim(offline)

R object with classes: ('integer',) mapped to:
<IntVector - Python:0x10d4fbd88 / R:0x7fb669f62ba8>
[1,181,629, 10]

In [166]:
offline[0]

NA_character_

In [169]:
offline[1]

'1139643118358'

In [171]:
new_offline = offline
r_base.dim(new_offline)

R object with classes: ('integer',) mapped to:
<IntVector - Python:0x10d404988 / R:0x7fb669f62ba8>
[1,181,629, 10]

In [173]:
new_offline[0]

NA_character_

In [186]:
#print(np.matrix(new_offline))
r_base.print(new_offline[0:10])

 [1]
 NA             
 "1139643118358"
 "1139643118358"
 "1139643118358"


 [5]
 "1139643118358"
 "1139643118358"
 "1139643118358"
 "1139643118358"


 [9]
 "1139643118358"
 "1139643118358"




R object with classes: ('character',) mapped to:
<StrVector - Python:0x10db686c8 / R:0x7fb669bc4f58>
[NA_character_, '11396431..., '11396431..., '11396431..., ..., '11396431..., '11396431..., '11396431..., '11396431...]

In [192]:
r_base.summary(offline)

R object with classes: ('table',) mapped to:
<Matrix - Python:0x10d4e9c08 / R:0x7fb66e03efa0>
['11396486..., '11396473..., '11396482..., '11396451..., ..., NA_character_, NA_character_, NA_character_, NA_character_]

In [208]:
r_base.length(offline)

R object with classes: ('integer',) mapped to:
<IntVector - Python:0x10db66448 / R:0x7fb666a82f48>
[11,816,290]

In [217]:
new_offline[0:10]

R object with classes: ('character',) mapped to:
<StrVector - Python:0x10de34888 / R:0x7fb670ed38a0>
[NA_character_, '11396431..., '11396431..., '11396431..., ..., '11396431..., '11396431..., '11396431..., '11396431...]

### Summary Statistics

> The summary statistics for each company are found below:
|
| Variable | Description |
| :------: | :---------: |
| t | Timestamp in milliseconds since midnight, January 1, 1970 UTC |
| id | MAC address of the scanning device |
| pos | The physical coordinate of the scanning device |
| degree | Orientation of the user carrying the scanning device in degrees |
| MAC | MAC address of a responding peer (e.g., an access point or a device in adhoc mode) with the corresponding values for signal strength in dBm (Decibel-milliwatts), the channel frequency and its mode (access point = 3, device in adhoc mode = 1) |

# <a name="Methods"></a>Methods

# <a name="Results"></a>Results

# <a name="Conclusion"></a>Future Work, Discussion, and Conclusion

# <a name="References"></a>References

1. 
2. 
3. 